//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.constantRent = new HashSet<constantRent>();
            this.disposableRent = new HashSet<disposableRent>();
        }
    
        public int carID { get; set; }
        public int onerID { get; set; }
        public Nullable<int> yearProduce { get; set; }
        public string model { get; set; }
        public Nullable<int> numSeats { get; set; }
        public Nullable<bool> babySeat { get; set; }
        public Nullable<int> priceForHour { get; set; }
        public string discription { get; set; }
        public Nullable<bool> handicappedCar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<constantRent> constantRent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<disposableRent> disposableRent { get; set; }
    }
}
