//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BRcarProjectEntities : DbContext
    {
        public BRcarProjectEntities()
            : base("name=BRcarProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<constantRent> constantRent { get; set; }
        public virtual DbSet<disposableRent> disposableRent { get; set; }
        public virtual DbSet<groupAtribution> groupAtribution { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<LoginRequests> LoginRequests { get; set; }
        public virtual DbSet<NotAllowForUser> NotAllowForUser { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
