//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int orderID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string startHour { get; set; }
        public string endHour { get; set; }
        public Nullable<int> numseats { get; set; }
        public Nullable<int> numHours { get; set; }
        public Nullable<int> rentID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
